AllCops:
  SuggestExtensions: false
  Exclude:
    - node_modules/**/*
    - bin/**/*
    - lib/tasks/cucumber.rake
  NewCops: enable 
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/HeredocIndentation:
  Exclude:
    - lib/tasks/default.rake
Metrics/BlockLength:
  Exclude:
    - db/schema.rb
