AllCops:
  SuggestExtensions: false
  Exclude:
    - node_modules/**/*
    - bin/**/*
    - lib/tasks/cucumber.rake
  NewCops: enable 
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/HeredocIndentation:
  Exclude:
    - lib/tasks/default.rake
Layout/LineLength:
  Exclude:
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - db/seeds.rb
Metrics/BlockLength:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - db/schema.rb
    - spec/controllers/businesses_controller_spec.rb
